networks:
  default:
    name: Strapi

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password  #Enter Your DB Root Password - Default is "password"
      MYSQL_DATABASE: strapi         #Enter Your DB Name - Default is "strapi"
      MYSQL_USER: strapi             #Enter Your DB User - Default is "strapi"
      MYSQL_PASSWORD: password       #Enter Your DB Password - Default is "password"
    volumes:
      - mysql_data:/var/lib/mysql

  strapi:
    build:
      context: . 
    container_name: strapi
    environment:
      DATABASE_CLIENT: mysql          # Enter your DB host address
      DATABASE_HOST: mysql            # Enter your DB host address
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi           #Enter Your DB Name - Default is "strapi"
      DATABASE_USERNAME: strapi       #Enter Your DB User - Default is "strapi"
      DATABASE_PASSWORD: password     #Enter Your DB Password - Default is "password"
    ports:
      - "1337:1337"
    depends_on:
      - mysql

volumes:
  mysql_data:
