services:
  unleash-db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: unleash_pass
    volumes:
      - db-data:/var/lib/postgresql/data

  unleash:
    image: unleashorg/unleash-server
    container_name: unleash
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: unleash-db
      DATABASE_NAME: unleash
      DATABASE_USERNAME: unleash_user
      DATABASE_PASSWORD: unleash_pass
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
      DATABASE_SSL: "false"
      LOG_LEVEL: debug
    depends_on:
      - unleash-db
  proxy:
    image: unleashorg/unleash-proxy
    container_name: unleash-proxy
    ports:
      - "3000:3000"
    environment:
      UNLEASH_URL: http://unleash:4242/api
      UNLEASH_API_TOKEN: "default:development.unleash-insecure-api-token" #Paste your CLIENT API Token copied from Unleash dashboard
      UNLEASH_PROXY_CLIENT_KEYS: "default:development.unleash-insecure-frontend-api-token" #Paste your FRONTEND API Token copied from Unleash dashboard
      UNLEASH_APP_NAME: frontend
      LOG_LEVEL: debug
    depends_on:
      - unleash

volumes:
  db-data:

networks:
  default:
    name : unleash-network