FROM node:22-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# -------- ENV for database config --------
ENV DATABASE_CLIENT=mysql
ENV DATABASE_HOST=mysql
ENV DATABASE_PORT=3306
ENV DATABASE_NAME=strapi
ENV DATABASE_USERNAME=strapi
ENV DATABASE_PASSWORD=password

#--------Copying Local App directory--------------
WORKDIR /strapi/
RUN echo "== Checking build context ==" && ls -al && ls -al ./test-strapi || echo "test-strapi not found"
RUN echo "Build context contents:" && ls -al && ls -al ./strapi/test-strapi || echo "strapi/test-strapi not found"

COPY . /strapi/

#--------Installing dependencies--------------
RUN npm install && npm install pg --save

EXPOSE 1337

CMD ["npm", "run", "develop"]
