networks:
  default:
    name: Strapi

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: strapi             #Enter Your DB Name - Default is "strapi"
      POSTGRES_USER: strapi           #Enter Your DB User - Default is "strapi"
      POSTGRES_PASSWORD: password     #Enter Your DB Password -Default is "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    image: kbalaji2212/projects:strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: postgres       
      DATABASE_HOST: postgres         # Enter your DB host address
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi           #Enter Your DB Name - Default is "strapi"
      DATABASE_USERNAME: strapi       #Enter Your DB User - Default is "strapi"
      DATABASE_PASSWORD: password     #Enter Your DB Password - Default is "password"
    depends_on:
      - postgres
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - strapi

volumes:
  postgres_data:
