name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: kbalaji2212/projects

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set dynamic image tag using GitHub run number
        id: set_tag
        run: |
          TAG="strapi-v${GITHUB_RUN_NUMBER}"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "$TAG" > image_tag.txt

      - name: Build and push Docker image
        working-directory: Day-7/strapi
        run: |
          docker build -t $IMAGE_REPO:$IMAGE_TAG .
          docker push $IMAGE_REPO:$IMAGE_TAG

      - name: Upload image tag
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt
