name: Blue-Green CodeDeploy Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Get Task Definition ARN
        run: |
          TASK_DEF_ARN=$(aws ecs describe-task-definition \
            --task-definition Strapi-Balaji \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Create AppSpec file
        run: |
          cat <<-EOF > appspec.yaml
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "${{ env.TASK_DEF_ARN }}"
        LoadBalancerInfo:
          ContainerName: "strapi-balaji"
          ContainerPort: 1337
EOF

      - name: Initiate CodeDeploy Deployment
        run: |

          ENCODED_CONTENT=$(base64 < appspec.yaml)
          ENCODED_HASH=$(openssl dgst -sha256 -binary appspec.yaml | openssl base64)

          aws deploy create-deployment \
            --application-name strapi-codedeploy-balaji \
            --deployment-group-name strapi-cd-deployment-group-balaji \
            --revision revisionType=AppSpecContent,appSpecContent="{\"content\":\"$ENCODED_CONTENT\",\"sha256\":\"$ENCODED_HASH\"}" \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
            --description "Triggered by GitHub Actions with task definition ${{ env.TASK_DEF_ARN }}"
